version: '3.4'

services:
    app:
        build: .\frontend
        environment:
            SERVER: http://server:3000/
        restart: always
        ports:
            - 80:80
        networks: 
            - frontend

    server:
        build: .\backend
        environment:
            HOST: redis_cache
            PORT: 6379
        restart: always
        ports:
            - '3000:80'
        networks: 
            - backend
            - frontend

    redis_cache:
        image: redis
        restart: always
        ports:
            - '6379:6379'
        networks: 
            - backend

networks: 
    backend:
    frontend: