version: '3.4'

services:
    app:
        build:
            context: ./frontend
            args:
                REACT_APP_PROTOCOL: http
                REACT_APP_SERVER: server
                REACT_APP_PORT: 3000
        restart: always
        ports:
            - 80:80
        networks: 
            - frontend
        depends_on: 
            - server

    server:
        build: ./backend
        environment:
            HOST: redis_cache
            PORT: 6379
        restart: always
        ports:
            - '3000:80'
        networks: 
            - backend
            - frontend
        depends_on: 
            - redis_cache
    
    redis_cache:
        image: redis
        restart: always
        ports:
            - '6379:6379'
        networks: 
            - backend

networks: 
    backend:
    frontend:
