version: '3.4'

services:
    app:
        build:
            context: ./frontend
            args:
                REACT_APP_SERVER_URI: http://3.16.40.249:3000     
        restart: always
        ports:
            - 80:80
        networks: 
            - frontend
        depends_on: 
            - server

    server:
        build: ./backend
        environment:
            REDIS_HOST: redis_cache
            REDIS_PORT: 6379
            LISTEN_PORT: 3000
        restart: always
        ports:
            - '3000:3000'
        networks: 
            - backend
            - frontend
        depends_on: 
            - redis_cache
    
    redis_cache:
        image: redis
        restart: always
        networks: 
            - backend

networks: 
    backend:
    frontend:
